<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:tns="http://www.mtb.com/webservices/wsdl/ESBService_v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://www.mtb.com/webservices/wsdl/ESBService_v1">
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <xs:import namespace="http://www.mtb.com/webservices/wsdl/ESBService_v1" schemaLocation="../../SharedResources/WSDL/ESBService_v1.xsd"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="fault">
        <wsdl:part element="tns:faultDetail" name="parameter"/>
    </wsdl:message>
</wsdl:definitions>