<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:tns="http://www.mtb.com/webservices/wsdl/SoapHeader_v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://www.mtb.com/webservices/wsdl/SoapHeader_v1">
    <wsdl:types>
        <xsi:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema">
            <xsi:import namespace="http://www.mtb.com/webservices/wsdl/SoapHeader_v1" schemaLocation="SoapHeader_v1.xsd"/>
        </xsi:schema>
    </wsdl:types>
    <wsdl:message name="ESBHeader">
        <wsdl:part element="tns:ESBHeader" name="ESBHeader"/>
    </wsdl:message>
</wsdl:definitions>