//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.10 at 05:13:42 PM EST 
//


package com.rsa.csd.oobsms.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rsa.csd.oobsms.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rsa.csd.oobsms.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OOBSMSAuthStatusRequest }
     * 
     */
    public OOBSMSAuthStatusRequest createOOBSMSAuthStatusRequest() {
        return new OOBSMSAuthStatusRequest();
    }

    /**
     * Create an instance of {@link OOBSMSAuthStatusResponse }
     * 
     */
    public OOBSMSAuthStatusResponse createOOBSMSAuthStatusResponse() {
        return new OOBSMSAuthStatusResponse();
    }

    /**
     * Create an instance of {@link OOBSMSAuthenticationRequest }
     * 
     */
    public OOBSMSAuthenticationRequest createOOBSMSAuthenticationRequest() {
        return new OOBSMSAuthenticationRequest();
    }

    /**
     * Create an instance of {@link OOBSMSAuthenticationResponse }
     * 
     */
    public OOBSMSAuthenticationResponse createOOBSMSAuthenticationResponse() {
        return new OOBSMSAuthenticationResponse();
    }

    /**
     * Create an instance of {@link OOBSMSChallengeRequest }
     * 
     */
    public OOBSMSChallengeRequest createOOBSMSChallengeRequest() {
        return new OOBSMSChallengeRequest();
    }

    /**
     * Create an instance of {@link OOBSMSChallengeResponse }
     * 
     */
    public OOBSMSChallengeResponse createOOBSMSChallengeResponse() {
        return new OOBSMSChallengeResponse();
    }

    /**
     * Create an instance of {@link OOBSMSManagementRequest }
     * 
     */
    public OOBSMSManagementRequest createOOBSMSManagementRequest() {
        return new OOBSMSManagementRequest();
    }

    /**
     * Create an instance of {@link OOBSMSManagementResponse }
     * 
     */
    public OOBSMSManagementResponse createOOBSMSManagementResponse() {
        return new OOBSMSManagementResponse();
    }

}
