//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.10 at 05:13:42 PM EST 
//


package com.rsa.csd.oobsms.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import com.rsa.csd.oobgen.ws.OOBGenManagementRequest;


/**
 * This type defines OOBSMS Management Request
 * 
 * <p>Java class for OOBSMSManagementRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OOBSMSManagementRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://ws.oobgen.csd.rsa.com}OOBGenManagementRequest"&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OOBSMSManagementRequest")
public class OOBSMSManagementRequest
    extends OOBGenManagementRequest
{


}
