//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.10 at 05:13:42 PM EST 
//


package com.rsa.csd.kba.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rsa.csd.kba.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rsa.csd.kba.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddressInfo }
     * 
     */
    public AddressInfo createAddressInfo() {
        return new AddressInfo();
    }

    /**
     * Create an instance of {@link Answer }
     * 
     */
    public Answer createAnswer() {
        return new Answer();
    }

    /**
     * Create an instance of {@link BirthdayInfo }
     * 
     */
    public BirthdayInfo createBirthdayInfo() {
        return new BirthdayInfo();
    }

    /**
     * Create an instance of {@link Choice }
     * 
     */
    public Choice createChoice() {
        return new Choice();
    }

    /**
     * Create an instance of {@link KBAAuthStatusRequest }
     * 
     */
    public KBAAuthStatusRequest createKBAAuthStatusRequest() {
        return new KBAAuthStatusRequest();
    }

    /**
     * Create an instance of {@link KBAAuthStatusResponse }
     * 
     */
    public KBAAuthStatusResponse createKBAAuthStatusResponse() {
        return new KBAAuthStatusResponse();
    }

    /**
     * Create an instance of {@link KBAAuthenticationRequest }
     * 
     */
    public KBAAuthenticationRequest createKBAAuthenticationRequest() {
        return new KBAAuthenticationRequest();
    }

    /**
     * Create an instance of {@link KBAAuthenticationResponse }
     * 
     */
    public KBAAuthenticationResponse createKBAAuthenticationResponse() {
        return new KBAAuthenticationResponse();
    }

    /**
     * Create an instance of {@link KBAChallengeRequest }
     * 
     */
    public KBAChallengeRequest createKBAChallengeRequest() {
        return new KBAChallengeRequest();
    }

    /**
     * Create an instance of {@link KBAChallengeResponse }
     * 
     */
    public KBAChallengeResponse createKBAChallengeResponse() {
        return new KBAChallengeResponse();
    }

    /**
     * Create an instance of {@link KBAManagementRequest }
     * 
     */
    public KBAManagementRequest createKBAManagementRequest() {
        return new KBAManagementRequest();
    }

    /**
     * Create an instance of {@link KBAManagementResponse }
     * 
     */
    public KBAManagementResponse createKBAManagementResponse() {
        return new KBAManagementResponse();
    }

    /**
     * Create an instance of {@link NameInfo }
     * 
     */
    public NameInfo createNameInfo() {
        return new NameInfo();
    }

    /**
     * Create an instance of {@link PersonInfo }
     * 
     */
    public PersonInfo createPersonInfo() {
        return new PersonInfo();
    }

    /**
     * Create an instance of {@link Question }
     * 
     */
    public Question createQuestion() {
        return new Question();
    }

    /**
     * Create an instance of {@link ResultStatus }
     * 
     */
    public ResultStatus createResultStatus() {
        return new ResultStatus();
    }

    /**
     * Create an instance of {@link SSNInfo }
     * 
     */
    public SSNInfo createSSNInfo() {
        return new SSNInfo();
    }

}
