//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.10 at 05:13:42 PM EST 
//


package com.rsa.csd.kba.ws;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SSNType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SSNType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SSN4"/&gt;
 *     &lt;enumeration value="SSN9"/&gt;
 *     &lt;enumeration value="SSN5"/&gt;
 *     &lt;enumeration value="OTHER"/&gt;
 *     &lt;enumeration value="NOSSN"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SSNType")
@XmlEnum
public enum SSNType {

    @XmlEnumValue("SSN4")
    SSN_4("SSN4"),
    @XmlEnumValue("SSN9")
    SSN_9("SSN9"),
    @XmlEnumValue("SSN5")
    SSN_5("SSN5"),
    OTHER("OTHER"),
    NOSSN("NOSSN");
    private final String value;

    SSNType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SSNType fromValue(String v) {
        for (SSNType c: SSNType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
