//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.10 at 05:13:42 PM EST 
//


package com.rsa.csd.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClientGenCookie complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClientGenCookie"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://ws.csd.rsa.com}DeviceIdentifier"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="clientGenCookie" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClientGenCookie", propOrder = {
    "clientGenCookie"
})
public class ClientGenCookie
    extends DeviceIdentifier
{

    protected String clientGenCookie;

    /**
     * Gets the value of the clientGenCookie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientGenCookie() {
        return clientGenCookie;
    }

    /**
     * Sets the value of the clientGenCookie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientGenCookie(String value) {
        this.clientGenCookie = value;
    }

}
