//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.10 at 05:13:42 PM EST 
//


package com.rsa.csd.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * This list returns a user's challenge material from the RSA System
 * 
 * <p>Java class for CredentialChallengeRequestList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CredentialChallengeRequestList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://ws.csd.rsa.com}CredentialRequestList"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="challengeQuestionChallengeRequest" type="{http://ws.csd.rsa.com}ChallengeQuestionChallengeRequest" minOccurs="0"/&gt;
 *         &lt;element name="oobEmailChallengeRequest" type="{http://ws.csd.rsa.com}OobEmailChallengeRequest" minOccurs="0"/&gt;
 *         &lt;element name="oobPhoneChallengeRequest" type="{http://ws.csd.rsa.com}OobPhoneChallengeRequest" minOccurs="0"/&gt;
 *         &lt;element name="acspChallengeRequestData" type="{http://ws.csd.rsa.com}AcspChallengeRequestData" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CredentialChallengeRequestList", propOrder = {
    "challengeQuestionChallengeRequest",
    "oobEmailChallengeRequest",
    "oobPhoneChallengeRequest",
    "acspChallengeRequestData"
})
public class CredentialChallengeRequestList
    extends CredentialRequestList
{

    protected ChallengeQuestionChallengeRequest challengeQuestionChallengeRequest;
    protected OobEmailChallengeRequest oobEmailChallengeRequest;
    protected OobPhoneChallengeRequest oobPhoneChallengeRequest;
    protected AcspChallengeRequestData acspChallengeRequestData;

    /**
     * Gets the value of the challengeQuestionChallengeRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ChallengeQuestionChallengeRequest }
     *     
     */
    public ChallengeQuestionChallengeRequest getChallengeQuestionChallengeRequest() {
        return challengeQuestionChallengeRequest;
    }

    /**
     * Sets the value of the challengeQuestionChallengeRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChallengeQuestionChallengeRequest }
     *     
     */
    public void setChallengeQuestionChallengeRequest(ChallengeQuestionChallengeRequest value) {
        this.challengeQuestionChallengeRequest = value;
    }

    /**
     * Gets the value of the oobEmailChallengeRequest property.
     * 
     * @return
     *     possible object is
     *     {@link OobEmailChallengeRequest }
     *     
     */
    public OobEmailChallengeRequest getOobEmailChallengeRequest() {
        return oobEmailChallengeRequest;
    }

    /**
     * Sets the value of the oobEmailChallengeRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link OobEmailChallengeRequest }
     *     
     */
    public void setOobEmailChallengeRequest(OobEmailChallengeRequest value) {
        this.oobEmailChallengeRequest = value;
    }

    /**
     * Gets the value of the oobPhoneChallengeRequest property.
     * 
     * @return
     *     possible object is
     *     {@link OobPhoneChallengeRequest }
     *     
     */
    public OobPhoneChallengeRequest getOobPhoneChallengeRequest() {
        return oobPhoneChallengeRequest;
    }

    /**
     * Sets the value of the oobPhoneChallengeRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link OobPhoneChallengeRequest }
     *     
     */
    public void setOobPhoneChallengeRequest(OobPhoneChallengeRequest value) {
        this.oobPhoneChallengeRequest = value;
    }

    /**
     * Gets the value of the acspChallengeRequestData property.
     * 
     * @return
     *     possible object is
     *     {@link AcspChallengeRequestData }
     *     
     */
    public AcspChallengeRequestData getAcspChallengeRequestData() {
        return acspChallengeRequestData;
    }

    /**
     * Sets the value of the acspChallengeRequestData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcspChallengeRequestData }
     *     
     */
    public void setAcspChallengeRequestData(AcspChallengeRequestData value) {
        this.acspChallengeRequestData = value;
    }

}
