//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.10 at 05:13:42 PM EST 
//


package com.rsa.csd.ws;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GenericActionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GenericActionType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="GET_USER_STATUS"/&gt;
 *     &lt;enumeration value="GET_USER_PREFERENCE"/&gt;
 *     &lt;enumeration value="GET_USER_GROUP"/&gt;
 *     &lt;enumeration value="GET_SYSTEM_CREDENTIAL"/&gt;
 *     &lt;enumeration value="GET_USER_CREDENTIAL"/&gt;
 *     &lt;enumeration value="GET_SYSTEM_CREDENTIAL_EXTENDED"/&gt;
 *     &lt;enumeration value="GET_USER_CREDENTIAL_EXTENDED"/&gt;
 *     &lt;enumeration value="BROWSE_USER_GROUP"/&gt;
 *     &lt;enumeration value="SET_USER_GROUP"/&gt;
 *     &lt;enumeration value="UPDATE_USER_NAME"/&gt;
 *     &lt;enumeration value="SET_USER_STATUS"/&gt;
 *     &lt;enumeration value="SET_USER_PREFERENCE"/&gt;
 *     &lt;enumeration value="ADD_FAVORITE"/&gt;
 *     &lt;enumeration value="DEL_FAVORITE"/&gt;
 *     &lt;enumeration value="CLEAR_FAVORITES"/&gt;
 *     &lt;enumeration value="GET_FAVORITES"/&gt;
 *     &lt;enumeration value="OPEN_SESSION"/&gt;
 *     &lt;enumeration value="CLOSE_SESSION"/&gt;
 *     &lt;enumeration value="COMMIT"/&gt;
 *     &lt;enumeration value="CANCEL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "GenericActionType")
@XmlEnum
public enum GenericActionType {

    GET_USER_STATUS,
    GET_USER_PREFERENCE,
    GET_USER_GROUP,
    GET_SYSTEM_CREDENTIAL,
    GET_USER_CREDENTIAL,
    GET_SYSTEM_CREDENTIAL_EXTENDED,
    GET_USER_CREDENTIAL_EXTENDED,
    BROWSE_USER_GROUP,
    SET_USER_GROUP,
    UPDATE_USER_NAME,
    SET_USER_STATUS,
    SET_USER_PREFERENCE,
    ADD_FAVORITE,
    DEL_FAVORITE,
    CLEAR_FAVORITES,
    GET_FAVORITES,
    OPEN_SESSION,
    CLOSE_SESSION,
    COMMIT,
    CANCEL;

    public String value() {
        return name();
    }

    public static GenericActionType fromValue(String v) {
        return valueOf(v);
    }

}
