//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.10 at 05:13:42 PM EST 
//


package com.rsa.csd.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rsa.csd.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SoapFault_QNAME = new QName("http://ws.csd.rsa.com", "SoapFault");
    private final static QName _UpdateUserReturn_QNAME = new QName("http://ws.csd.rsa.com", "updateUserReturn");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rsa.csd.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SoapFaultType }
     * 
     */
    public SoapFaultType createSoapFaultType() {
        return new SoapFaultType();
    }

    /**
     * Create an instance of {@link Analyze }
     * 
     */
    public Analyze createAnalyze() {
        return new Analyze();
    }

    /**
     * Create an instance of {@link AnalyzeRequest }
     * 
     */
    public AnalyzeRequest createAnalyzeRequest() {
        return new AnalyzeRequest();
    }

    /**
     * Create an instance of {@link AnalyzeResponse }
     * 
     */
    public AnalyzeResponse createAnalyzeResponse() {
        return new AnalyzeResponse();
    }

    /**
     * Create an instance of {@link AnalyzeResponse2 }
     * 
     */
    public AnalyzeResponse2 createAnalyzeResponse2() {
        return new AnalyzeResponse2();
    }

    /**
     * Create an instance of {@link Authenticate }
     * 
     */
    public Authenticate createAuthenticate() {
        return new Authenticate();
    }

    /**
     * Create an instance of {@link AuthenticateRequest }
     * 
     */
    public AuthenticateRequest createAuthenticateRequest() {
        return new AuthenticateRequest();
    }

    /**
     * Create an instance of {@link AuthenticateResponse }
     * 
     */
    public AuthenticateResponse createAuthenticateResponse() {
        return new AuthenticateResponse();
    }

    /**
     * Create an instance of {@link AuthenticateResponse2 }
     * 
     */
    public AuthenticateResponse2 createAuthenticateResponse2() {
        return new AuthenticateResponse2();
    }

    /**
     * Create an instance of {@link Challenge }
     * 
     */
    public Challenge createChallenge() {
        return new Challenge();
    }

    /**
     * Create an instance of {@link ChallengeRequest }
     * 
     */
    public ChallengeRequest createChallengeRequest() {
        return new ChallengeRequest();
    }

    /**
     * Create an instance of {@link ChallengeResponse }
     * 
     */
    public ChallengeResponse createChallengeResponse() {
        return new ChallengeResponse();
    }

    /**
     * Create an instance of {@link ChallengeResponse2 }
     * 
     */
    public ChallengeResponse2 createChallengeResponse2() {
        return new ChallengeResponse2();
    }

    /**
     * Create an instance of {@link CreateUser }
     * 
     */
    public CreateUser createCreateUser() {
        return new CreateUser();
    }

    /**
     * Create an instance of {@link CreateUserRequest }
     * 
     */
    public CreateUserRequest createCreateUserRequest() {
        return new CreateUserRequest();
    }

    /**
     * Create an instance of {@link CreateUserResponse }
     * 
     */
    public CreateUserResponse createCreateUserResponse() {
        return new CreateUserResponse();
    }

    /**
     * Create an instance of {@link CreateUserResponse2 }
     * 
     */
    public CreateUserResponse2 createCreateUserResponse2() {
        return new CreateUserResponse2();
    }

    /**
     * Create an instance of {@link Notify }
     * 
     */
    public Notify createNotify() {
        return new Notify();
    }

    /**
     * Create an instance of {@link NotifyRequest }
     * 
     */
    public NotifyRequest createNotifyRequest() {
        return new NotifyRequest();
    }

    /**
     * Create an instance of {@link NotifyResponse }
     * 
     */
    public NotifyResponse createNotifyResponse() {
        return new NotifyResponse();
    }

    /**
     * Create an instance of {@link NotifyResponse2 }
     * 
     */
    public NotifyResponse2 createNotifyResponse2() {
        return new NotifyResponse2();
    }

    /**
     * Create an instance of {@link Query }
     * 
     */
    public Query createQuery() {
        return new Query();
    }

    /**
     * Create an instance of {@link QueryRequest }
     * 
     */
    public QueryRequest createQueryRequest() {
        return new QueryRequest();
    }

    /**
     * Create an instance of {@link QueryAuthStatus }
     * 
     */
    public QueryAuthStatus createQueryAuthStatus() {
        return new QueryAuthStatus();
    }

    /**
     * Create an instance of {@link QueryAuthStatusRequest }
     * 
     */
    public QueryAuthStatusRequest createQueryAuthStatusRequest() {
        return new QueryAuthStatusRequest();
    }

    /**
     * Create an instance of {@link QueryAuthStatusResponse }
     * 
     */
    public QueryAuthStatusResponse createQueryAuthStatusResponse() {
        return new QueryAuthStatusResponse();
    }

    /**
     * Create an instance of {@link QueryAuthStatusResponse2 }
     * 
     */
    public QueryAuthStatusResponse2 createQueryAuthStatusResponse2() {
        return new QueryAuthStatusResponse2();
    }

    /**
     * Create an instance of {@link QueryResponse }
     * 
     */
    public QueryResponse createQueryResponse() {
        return new QueryResponse();
    }

    /**
     * Create an instance of {@link QueryResponse2 }
     * 
     */
    public QueryResponse2 createQueryResponse2() {
        return new QueryResponse2();
    }

    /**
     * Create an instance of {@link UpdateUser }
     * 
     */
    public UpdateUser createUpdateUser() {
        return new UpdateUser();
    }

    /**
     * Create an instance of {@link UpdateUserRequest }
     * 
     */
    public UpdateUserRequest createUpdateUserRequest() {
        return new UpdateUserRequest();
    }

    /**
     * Create an instance of {@link UpdateUserResponse }
     * 
     */
    public UpdateUserResponse createUpdateUserResponse() {
        return new UpdateUserResponse();
    }

    /**
     * Create an instance of {@link UpdateUserResponse2 }
     * 
     */
    public UpdateUserResponse2 createUpdateUserResponse2() {
        return new UpdateUserResponse2();
    }

    /**
     * Create an instance of {@link AccountData }
     * 
     */
    public AccountData createAccountData() {
        return new AccountData();
    }

    /**
     * Create an instance of {@link AcspAuthStatusRequestData }
     * 
     */
    public AcspAuthStatusRequestData createAcspAuthStatusRequestData() {
        return new AcspAuthStatusRequestData();
    }

    /**
     * Create an instance of {@link AcspAuthStatusResponseData }
     * 
     */
    public AcspAuthStatusResponseData createAcspAuthStatusResponseData() {
        return new AcspAuthStatusResponseData();
    }

    /**
     * Create an instance of {@link AcspAuthenticationRequestData }
     * 
     */
    public AcspAuthenticationRequestData createAcspAuthenticationRequestData() {
        return new AcspAuthenticationRequestData();
    }

    /**
     * Create an instance of {@link AcspAuthenticationResponseData }
     * 
     */
    public AcspAuthenticationResponseData createAcspAuthenticationResponseData() {
        return new AcspAuthenticationResponseData();
    }

    /**
     * Create an instance of {@link AcspChallengeRequestData }
     * 
     */
    public AcspChallengeRequestData createAcspChallengeRequestData() {
        return new AcspChallengeRequestData();
    }

    /**
     * Create an instance of {@link AcspChallengeResponseData }
     * 
     */
    public AcspChallengeResponseData createAcspChallengeResponseData() {
        return new AcspChallengeResponseData();
    }

    /**
     * Create an instance of {@link AcspManagementRequestData }
     * 
     */
    public AcspManagementRequestData createAcspManagementRequestData() {
        return new AcspManagementRequestData();
    }

    /**
     * Create an instance of {@link AcspManagementResponseData }
     * 
     */
    public AcspManagementResponseData createAcspManagementResponseData() {
        return new AcspManagementResponseData();
    }

    /**
     * Create an instance of {@link ActionTypeList }
     * 
     */
    public ActionTypeList createActionTypeList() {
        return new ActionTypeList();
    }

    /**
     * Create an instance of {@link AuthenticationLevel }
     * 
     */
    public AuthenticationLevel createAuthenticationLevel() {
        return new AuthenticationLevel();
    }

    /**
     * Create an instance of {@link AuthenticationResult }
     * 
     */
    public AuthenticationResult createAuthenticationResult() {
        return new AuthenticationResult();
    }

    /**
     * Create an instance of {@link CallStatus }
     * 
     */
    public CallStatus createCallStatus() {
        return new CallStatus();
    }

    /**
     * Create an instance of {@link ChallengeQuestion }
     * 
     */
    public ChallengeQuestion createChallengeQuestion() {
        return new ChallengeQuestion();
    }

    /**
     * Create an instance of {@link ChallengeQuestionActionTypeList }
     * 
     */
    public ChallengeQuestionActionTypeList createChallengeQuestionActionTypeList() {
        return new ChallengeQuestionActionTypeList();
    }

    /**
     * Create an instance of {@link ChallengeQuestionAuthResult }
     * 
     */
    public ChallengeQuestionAuthResult createChallengeQuestionAuthResult() {
        return new ChallengeQuestionAuthResult();
    }

    /**
     * Create an instance of {@link ChallengeQuestionAuthResultPayload }
     * 
     */
    public ChallengeQuestionAuthResultPayload createChallengeQuestionAuthResultPayload() {
        return new ChallengeQuestionAuthResultPayload();
    }

    /**
     * Create an instance of {@link ChallengeQuestionAuthStatusRequest }
     * 
     */
    public ChallengeQuestionAuthStatusRequest createChallengeQuestionAuthStatusRequest() {
        return new ChallengeQuestionAuthStatusRequest();
    }

    /**
     * Create an instance of {@link ChallengeQuestionAuthStatusResponse }
     * 
     */
    public ChallengeQuestionAuthStatusResponse createChallengeQuestionAuthStatusResponse() {
        return new ChallengeQuestionAuthStatusResponse();
    }

    /**
     * Create an instance of {@link ChallengeQuestionChallenge }
     * 
     */
    public ChallengeQuestionChallenge createChallengeQuestionChallenge() {
        return new ChallengeQuestionChallenge();
    }

    /**
     * Create an instance of {@link ChallengeQuestionChallengePayload }
     * 
     */
    public ChallengeQuestionChallengePayload createChallengeQuestionChallengePayload() {
        return new ChallengeQuestionChallengePayload();
    }

    /**
     * Create an instance of {@link ChallengeQuestionChallengeRequest }
     * 
     */
    public ChallengeQuestionChallengeRequest createChallengeQuestionChallengeRequest() {
        return new ChallengeQuestionChallengeRequest();
    }

    /**
     * Create an instance of {@link ChallengeQuestionChallengeRequestPayload }
     * 
     */
    public ChallengeQuestionChallengeRequestPayload createChallengeQuestionChallengeRequestPayload() {
        return new ChallengeQuestionChallengeRequestPayload();
    }

    /**
     * Create an instance of {@link ChallengeQuestionConfig }
     * 
     */
    public ChallengeQuestionConfig createChallengeQuestionConfig() {
        return new ChallengeQuestionConfig();
    }

    /**
     * Create an instance of {@link ChallengeQuestionData }
     * 
     */
    public ChallengeQuestionData createChallengeQuestionData() {
        return new ChallengeQuestionData();
    }

    /**
     * Create an instance of {@link ChallengeQuestionDataPayload }
     * 
     */
    public ChallengeQuestionDataPayload createChallengeQuestionDataPayload() {
        return new ChallengeQuestionDataPayload();
    }

    /**
     * Create an instance of {@link ChallengeQuestionGroup }
     * 
     */
    public ChallengeQuestionGroup createChallengeQuestionGroup() {
        return new ChallengeQuestionGroup();
    }

    /**
     * Create an instance of {@link ChallengeQuestionGroupList }
     * 
     */
    public ChallengeQuestionGroupList createChallengeQuestionGroupList() {
        return new ChallengeQuestionGroupList();
    }

    /**
     * Create an instance of {@link ChallengeQuestionIdList }
     * 
     */
    public ChallengeQuestionIdList createChallengeQuestionIdList() {
        return new ChallengeQuestionIdList();
    }

    /**
     * Create an instance of {@link ChallengeQuestionList }
     * 
     */
    public ChallengeQuestionList createChallengeQuestionList() {
        return new ChallengeQuestionList();
    }

    /**
     * Create an instance of {@link ChallengeQuestionManagementRequest }
     * 
     */
    public ChallengeQuestionManagementRequest createChallengeQuestionManagementRequest() {
        return new ChallengeQuestionManagementRequest();
    }

    /**
     * Create an instance of {@link ChallengeQuestionManagementRequestPayload }
     * 
     */
    public ChallengeQuestionManagementRequestPayload createChallengeQuestionManagementRequestPayload() {
        return new ChallengeQuestionManagementRequestPayload();
    }

    /**
     * Create an instance of {@link ChallengeQuestionManagementResponse }
     * 
     */
    public ChallengeQuestionManagementResponse createChallengeQuestionManagementResponse() {
        return new ChallengeQuestionManagementResponse();
    }

    /**
     * Create an instance of {@link ChallengeQuestionManagementResponsePayload }
     * 
     */
    public ChallengeQuestionManagementResponsePayload createChallengeQuestionManagementResponsePayload() {
        return new ChallengeQuestionManagementResponsePayload();
    }

    /**
     * Create an instance of {@link ChallengeQuestionMatchResult }
     * 
     */
    public ChallengeQuestionMatchResult createChallengeQuestionMatchResult() {
        return new ChallengeQuestionMatchResult();
    }

    /**
     * Create an instance of {@link ClientDefinedFact }
     * 
     */
    public ClientDefinedFact createClientDefinedFact() {
        return new ClientDefinedFact();
    }

    /**
     * Create an instance of {@link ClientGenCookie }
     * 
     */
    public ClientGenCookie createClientGenCookie() {
        return new ClientGenCookie();
    }

    /**
     * Create an instance of {@link ClientReturnData }
     * 
     */
    public ClientReturnData createClientReturnData() {
        return new ClientReturnData();
    }

    /**
     * Create an instance of {@link CollectableCredential }
     * 
     */
    public CollectableCredential createCollectableCredential() {
        return new CollectableCredential();
    }

    /**
     * Create an instance of {@link CollectableCredentialList }
     * 
     */
    public CollectableCredentialList createCollectableCredentialList() {
        return new CollectableCredentialList();
    }

    /**
     * Create an instance of {@link CollectionRequest }
     * 
     */
    public CollectionRequest createCollectionRequest() {
        return new CollectionRequest();
    }

    /**
     * Create an instance of {@link ConfigurationHeader }
     * 
     */
    public ConfigurationHeader createConfigurationHeader() {
        return new ConfigurationHeader();
    }

    /**
     * Create an instance of {@link Credential }
     * 
     */
    public Credential createCredential() {
        return new Credential();
    }

    /**
     * Create an instance of {@link CredentialAuthResultList }
     * 
     */
    public CredentialAuthResultList createCredentialAuthResultList() {
        return new CredentialAuthResultList();
    }

    /**
     * Create an instance of {@link CredentialAuthStatusRequest }
     * 
     */
    public CredentialAuthStatusRequest createCredentialAuthStatusRequest() {
        return new CredentialAuthStatusRequest();
    }

    /**
     * Create an instance of {@link CredentialAuthStatusResponse }
     * 
     */
    public CredentialAuthStatusResponse createCredentialAuthStatusResponse() {
        return new CredentialAuthStatusResponse();
    }

    /**
     * Create an instance of {@link CredentialChallengeList }
     * 
     */
    public CredentialChallengeList createCredentialChallengeList() {
        return new CredentialChallengeList();
    }

    /**
     * Create an instance of {@link CredentialChallengeRequestList }
     * 
     */
    public CredentialChallengeRequestList createCredentialChallengeRequestList() {
        return new CredentialChallengeRequestList();
    }

    /**
     * Create an instance of {@link CredentialDataList }
     * 
     */
    public CredentialDataList createCredentialDataList() {
        return new CredentialDataList();
    }

    /**
     * Create an instance of {@link CredentialList }
     * 
     */
    public CredentialList createCredentialList() {
        return new CredentialList();
    }

    /**
     * Create an instance of {@link CredentialManagementRequestList }
     * 
     */
    public CredentialManagementRequestList createCredentialManagementRequestList() {
        return new CredentialManagementRequestList();
    }

    /**
     * Create an instance of {@link CredentialManagementResponseList }
     * 
     */
    public CredentialManagementResponseList createCredentialManagementResponseList() {
        return new CredentialManagementResponseList();
    }

    /**
     * Create an instance of {@link DeviceActionTypeList }
     * 
     */
    public DeviceActionTypeList createDeviceActionTypeList() {
        return new DeviceActionTypeList();
    }

    /**
     * Create an instance of {@link DeviceData }
     * 
     */
    public DeviceData createDeviceData() {
        return new DeviceData();
    }

    /**
     * Create an instance of {@link DeviceManagementRequestPayload }
     * 
     */
    public DeviceManagementRequestPayload createDeviceManagementRequestPayload() {
        return new DeviceManagementRequestPayload();
    }

    /**
     * Create an instance of {@link DeviceManagementResponsePayload }
     * 
     */
    public DeviceManagementResponsePayload createDeviceManagementResponsePayload() {
        return new DeviceManagementResponsePayload();
    }

    /**
     * Create an instance of {@link DeviceRequest }
     * 
     */
    public DeviceRequest createDeviceRequest() {
        return new DeviceRequest();
    }

    /**
     * Create an instance of {@link DeviceResult }
     * 
     */
    public DeviceResult createDeviceResult() {
        return new DeviceResult();
    }

    /**
     * Create an instance of {@link EmailInfo }
     * 
     */
    public EmailInfo createEmailInfo() {
        return new EmailInfo();
    }

    /**
     * Create an instance of {@link EmailManagementRequestPayload }
     * 
     */
    public EmailManagementRequestPayload createEmailManagementRequestPayload() {
        return new EmailManagementRequestPayload();
    }

    /**
     * Create an instance of {@link EmailManagementResponsePayload }
     * 
     */
    public EmailManagementResponsePayload createEmailManagementResponsePayload() {
        return new EmailManagementResponsePayload();
    }

    /**
     * Create an instance of {@link EventData }
     * 
     */
    public EventData createEventData() {
        return new EventData();
    }

    /**
     * Create an instance of {@link EventDataList }
     * 
     */
    public EventDataList createEventDataList() {
        return new EventDataList();
    }

    /**
     * Create an instance of {@link FactList }
     * 
     */
    public FactList createFactList() {
        return new FactList();
    }

    /**
     * Create an instance of {@link GenericActionTypeList }
     * 
     */
    public GenericActionTypeList createGenericActionTypeList() {
        return new GenericActionTypeList();
    }

    /**
     * Create an instance of {@link GeoLocation }
     * 
     */
    public GeoLocation createGeoLocation() {
        return new GeoLocation();
    }

    /**
     * Create an instance of {@link IdentificationData }
     * 
     */
    public IdentificationData createIdentificationData() {
        return new IdentificationData();
    }

    /**
     * Create an instance of {@link MessageHeader }
     * 
     */
    public MessageHeader createMessageHeader() {
        return new MessageHeader();
    }

    /**
     * Create an instance of {@link MobileDevice }
     * 
     */
    public MobileDevice createMobileDevice() {
        return new MobileDevice();
    }

    /**
     * Create an instance of {@link NamedValue }
     * 
     */
    public NamedValue createNamedValue() {
        return new NamedValue();
    }

    /**
     * Create an instance of {@link OOBActionTypeList }
     * 
     */
    public OOBActionTypeList createOOBActionTypeList() {
        return new OOBActionTypeList();
    }

    /**
     * Create an instance of {@link OOBContactInfoObject }
     * 
     */
    public OOBContactInfoObject createOOBContactInfoObject() {
        return new OOBContactInfoObject();
    }

    /**
     * Create an instance of {@link OOBEmailChallengeRequestPayload }
     * 
     */
    public OOBEmailChallengeRequestPayload createOOBEmailChallengeRequestPayload() {
        return new OOBEmailChallengeRequestPayload();
    }

    /**
     * Create an instance of {@link OOBInfoRequestPayload }
     * 
     */
    public OOBInfoRequestPayload createOOBInfoRequestPayload() {
        return new OOBInfoRequestPayload();
    }

    /**
     * Create an instance of {@link OOBInfoResponsePayload }
     * 
     */
    public OOBInfoResponsePayload createOOBInfoResponsePayload() {
        return new OOBInfoResponsePayload();
    }

    /**
     * Create an instance of {@link OOBPhoneChallengeRequestPayload }
     * 
     */
    public OOBPhoneChallengeRequestPayload createOOBPhoneChallengeRequestPayload() {
        return new OOBPhoneChallengeRequestPayload();
    }

    /**
     * Create an instance of {@link OobEmailAuthResult }
     * 
     */
    public OobEmailAuthResult createOobEmailAuthResult() {
        return new OobEmailAuthResult();
    }

    /**
     * Create an instance of {@link OobEmailAuthStatusRequest }
     * 
     */
    public OobEmailAuthStatusRequest createOobEmailAuthStatusRequest() {
        return new OobEmailAuthStatusRequest();
    }

    /**
     * Create an instance of {@link OobEmailAuthStatusResponse }
     * 
     */
    public OobEmailAuthStatusResponse createOobEmailAuthStatusResponse() {
        return new OobEmailAuthStatusResponse();
    }

    /**
     * Create an instance of {@link OobEmailChallenge }
     * 
     */
    public OobEmailChallenge createOobEmailChallenge() {
        return new OobEmailChallenge();
    }

    /**
     * Create an instance of {@link OobEmailChallengeRequest }
     * 
     */
    public OobEmailChallengeRequest createOobEmailChallengeRequest() {
        return new OobEmailChallengeRequest();
    }

    /**
     * Create an instance of {@link OobEmailData }
     * 
     */
    public OobEmailData createOobEmailData() {
        return new OobEmailData();
    }

    /**
     * Create an instance of {@link OobEmailManagementRequest }
     * 
     */
    public OobEmailManagementRequest createOobEmailManagementRequest() {
        return new OobEmailManagementRequest();
    }

    /**
     * Create an instance of {@link OobEmailManagementResponse }
     * 
     */
    public OobEmailManagementResponse createOobEmailManagementResponse() {
        return new OobEmailManagementResponse();
    }

    /**
     * Create an instance of {@link OobPhoneAuthResult }
     * 
     */
    public OobPhoneAuthResult createOobPhoneAuthResult() {
        return new OobPhoneAuthResult();
    }

    /**
     * Create an instance of {@link OobPhoneAuthStatusRequest }
     * 
     */
    public OobPhoneAuthStatusRequest createOobPhoneAuthStatusRequest() {
        return new OobPhoneAuthStatusRequest();
    }

    /**
     * Create an instance of {@link OobPhoneAuthStatusResponse }
     * 
     */
    public OobPhoneAuthStatusResponse createOobPhoneAuthStatusResponse() {
        return new OobPhoneAuthStatusResponse();
    }

    /**
     * Create an instance of {@link OobPhoneChallenge }
     * 
     */
    public OobPhoneChallenge createOobPhoneChallenge() {
        return new OobPhoneChallenge();
    }

    /**
     * Create an instance of {@link OobPhoneChallengeRequest }
     * 
     */
    public OobPhoneChallengeRequest createOobPhoneChallengeRequest() {
        return new OobPhoneChallengeRequest();
    }

    /**
     * Create an instance of {@link OobPhoneData }
     * 
     */
    public OobPhoneData createOobPhoneData() {
        return new OobPhoneData();
    }

    /**
     * Create an instance of {@link OobPhoneManagementRequest }
     * 
     */
    public OobPhoneManagementRequest createOobPhoneManagementRequest() {
        return new OobPhoneManagementRequest();
    }

    /**
     * Create an instance of {@link OobPhoneManagementResponse }
     * 
     */
    public OobPhoneManagementResponse createOobPhoneManagementResponse() {
        return new OobPhoneManagementResponse();
    }

    /**
     * Create an instance of {@link PhoneData }
     * 
     */
    public PhoneData createPhoneData() {
        return new PhoneData();
    }

    /**
     * Create an instance of {@link PhoneInfo }
     * 
     */
    public PhoneInfo createPhoneInfo() {
        return new PhoneInfo();
    }

    /**
     * Create an instance of {@link PhoneManagementRequestPayload }
     * 
     */
    public PhoneManagementRequestPayload createPhoneManagementRequestPayload() {
        return new PhoneManagementRequestPayload();
    }

    /**
     * Create an instance of {@link PhoneManagementResponsePayload }
     * 
     */
    public PhoneManagementResponsePayload createPhoneManagementResponsePayload() {
        return new PhoneManagementResponsePayload();
    }

    /**
     * Create an instance of {@link RequiredCredential }
     * 
     */
    public RequiredCredential createRequiredCredential() {
        return new RequiredCredential();
    }

    /**
     * Create an instance of {@link RequiredCredentialList }
     * 
     */
    public RequiredCredentialList createRequiredCredentialList() {
        return new RequiredCredentialList();
    }

    /**
     * Create an instance of {@link RiskResult }
     * 
     */
    public RiskResult createRiskResult() {
        return new RiskResult();
    }

    /**
     * Create an instance of {@link SecurityHeader }
     * 
     */
    public SecurityHeader createSecurityHeader() {
        return new SecurityHeader();
    }

    /**
     * Create an instance of {@link ServerRedirectData }
     * 
     */
    public ServerRedirectData createServerRedirectData() {
        return new ServerRedirectData();
    }

    /**
     * Create an instance of {@link StatusHeader }
     * 
     */
    public StatusHeader createStatusHeader() {
        return new StatusHeader();
    }

    /**
     * Create an instance of {@link StockData }
     * 
     */
    public StockData createStockData() {
        return new StockData();
    }

    /**
     * Create an instance of {@link StockTradeData }
     * 
     */
    public StockTradeData createStockTradeData() {
        return new StockTradeData();
    }

    /**
     * Create an instance of {@link TransactionData }
     * 
     */
    public TransactionData createTransactionData() {
        return new TransactionData();
    }

    /**
     * Create an instance of {@link TriggeredRule }
     * 
     */
    public TriggeredRule createTriggeredRule() {
        return new TriggeredRule();
    }

    /**
     * Create an instance of {@link UnsupportedAuthStatusRequestPayload }
     * 
     */
    public UnsupportedAuthStatusRequestPayload createUnsupportedAuthStatusRequestPayload() {
        return new UnsupportedAuthStatusRequestPayload();
    }

    /**
     * Create an instance of {@link UnsupportedAuthStatusResponsePayload }
     * 
     */
    public UnsupportedAuthStatusResponsePayload createUnsupportedAuthStatusResponsePayload() {
        return new UnsupportedAuthStatusResponsePayload();
    }

    /**
     * Create an instance of {@link UnsupportedChallengePayload }
     * 
     */
    public UnsupportedChallengePayload createUnsupportedChallengePayload() {
        return new UnsupportedChallengePayload();
    }

    /**
     * Create an instance of {@link UnsupportedChallengeRequestPayload }
     * 
     */
    public UnsupportedChallengeRequestPayload createUnsupportedChallengeRequestPayload() {
        return new UnsupportedChallengeRequestPayload();
    }

    /**
     * Create an instance of {@link UserAddress }
     * 
     */
    public UserAddress createUserAddress() {
        return new UserAddress();
    }

    /**
     * Create an instance of {@link UserData }
     * 
     */
    public UserData createUserData() {
        return new UserData();
    }

    /**
     * Create an instance of {@link UserName }
     * 
     */
    public UserName createUserName() {
        return new UserName();
    }

    /**
     * Create an instance of {@link UserPreference }
     * 
     */
    public UserPreference createUserPreference() {
        return new UserPreference();
    }

    /**
     * Create an instance of {@link WiFiNetworkData }
     * 
     */
    public WiFiNetworkData createWiFiNetworkData() {
        return new WiFiNetworkData();
    }

    /**
     * Create an instance of {@link OTPAuthStatusRequest }
     * 
     */
    public OTPAuthStatusRequest createOTPAuthStatusRequest() {
        return new OTPAuthStatusRequest();
    }

    /**
     * Create an instance of {@link OTPAuthStatusResponse }
     * 
     */
    public OTPAuthStatusResponse createOTPAuthStatusResponse() {
        return new OTPAuthStatusResponse();
    }

    /**
     * Create an instance of {@link OTPAuthenticationRequest }
     * 
     */
    public OTPAuthenticationRequest createOTPAuthenticationRequest() {
        return new OTPAuthenticationRequest();
    }

    /**
     * Create an instance of {@link OTPAuthenticationResponse }
     * 
     */
    public OTPAuthenticationResponse createOTPAuthenticationResponse() {
        return new OTPAuthenticationResponse();
    }

    /**
     * Create an instance of {@link OTPChallengeRequest }
     * 
     */
    public OTPChallengeRequest createOTPChallengeRequest() {
        return new OTPChallengeRequest();
    }

    /**
     * Create an instance of {@link OTPChallengeResponse }
     * 
     */
    public OTPChallengeResponse createOTPChallengeResponse() {
        return new OTPChallengeResponse();
    }

    /**
     * Create an instance of {@link OTPManagementRequest }
     * 
     */
    public OTPManagementRequest createOTPManagementRequest() {
        return new OTPManagementRequest();
    }

    /**
     * Create an instance of {@link OTPManagementResponse }
     * 
     */
    public OTPManagementResponse createOTPManagementResponse() {
        return new OTPManagementResponse();
    }

    /**
     * Create an instance of {@link Amount }
     * 
     */
    public Amount createAmount() {
        return new Amount();
    }

    /**
     * Create an instance of {@link Coordinates }
     * 
     */
    public Coordinates createCoordinates() {
        return new Coordinates();
    }

    /**
     * Create an instance of {@link ATM }
     * 
     */
    public ATM createATM() {
        return new ATM();
    }

    /**
     * Create an instance of {@link ATMLocation }
     * 
     */
    public ATMLocation createATMLocation() {
        return new ATMLocation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoapFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.csd.rsa.com", name = "SoapFault")
    public JAXBElement<SoapFaultType> createSoapFault(SoapFaultType value) {
        return new JAXBElement<SoapFaultType>(_SoapFault_QNAME, SoapFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateUserResponse2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.csd.rsa.com", name = "updateUserReturn")
    public JAXBElement<UpdateUserResponse2> createUpdateUserReturn(UpdateUserResponse2 value) {
        return new JAXBElement<UpdateUserResponse2>(_UpdateUserReturn_QNAME, UpdateUserResponse2 .class, null, value);
    }

}
