//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.10 at 05:13:42 PM EST 
//


package com.rsa.csd.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * This defines the contents of a QUERYAUTHSTATUS response
 * 
 * <p>Java class for QueryAuthStatusResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryAuthStatusResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://ws.csd.rsa.com}GenericResponse"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="credentialAuthStatusResponse" type="{http://ws.csd.rsa.com}CredentialAuthStatusResponse" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryAuthStatusResponse", propOrder = {
    "credentialAuthStatusResponse"
})
public class QueryAuthStatusResponse2
    extends GenericResponse
{

    protected CredentialAuthStatusResponse credentialAuthStatusResponse;

    /**
     * Gets the value of the credentialAuthStatusResponse property.
     * 
     * @return
     *     possible object is
     *     {@link CredentialAuthStatusResponse }
     *     
     */
    public CredentialAuthStatusResponse getCredentialAuthStatusResponse() {
        return credentialAuthStatusResponse;
    }

    /**
     * Sets the value of the credentialAuthStatusResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link CredentialAuthStatusResponse }
     *     
     */
    public void setCredentialAuthStatusResponse(CredentialAuthStatusResponse value) {
        this.credentialAuthStatusResponse = value;
    }

}
